// PLAYER REDUCER 
export const SET_CURRENT_INDEX = 'SET_CURRENT_INDEX';
export const SET_PLAYLIST = 'SET_PLAYLIST';
export const SET_LOADING = 'SET_LOADING';

// FAVS REDUCER
export const ADD_TO_FOLLOW = 'ADD_TO_FOLLOW';
export const REMOVE_FROM_FOLLOW = 'REMOVE_FROM_FOLLOW';