// PLAYER REDUCER 
export const SET_CURRENT_SONG = 'SET_CURRENT_SONG';
export const TOGGLE_PLAYING = 'TOGGLE_PLAYING';
export const SET_CURRENT_SONG_INDEX = 'SET_CURRENT_SONG_INDEX';
export const SET_PLAYLIST = 'SET_PLAYLIST';
export const SET_LOADING = 'SET_LOADING';

// FAVS REDUCER
export const ADD_TO_FOLLOW = 'ADD_TO_FOLLOW';
export const REMOVE_FROM_FOLLOW = 'REMOVE_FROM_FOLLOW';